### PR TITLE
can't find composer.json file in var/www/... address /var/www/... is …

### PR DESCRIPTION
**Pull request by zhitoo**
…correct

### CODE REVIEW

**Comment by zhitoo** [comment]
system cant find compose.json file in this address var/www/.....    
i added an / the begining of base path

**Comment by imanghafoori1** [comment]
This is not correct.

**Comment by zhitoo** [comment]
> This is not correct.

but test not running with relative path

**Comment by imanghafoori1** [comment]
Mention your OS and exact PHP version of failing tests.

**Comment by zhitoo** [comment]
> Mention your OS and exact PHP version of failing tests.

run on docker( php8.1 and ubuntu 22 ) using laravel sail

**Comment by imanghafoori1** [comment]
It is now fixed and the tests are passing.

**Pull request closed without merging**
